create table PS_POLICY
(
  ID            INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  RULE          TEXT NOT NULL,
  ACTION        INTEGER NOT NULL,
  POLICY_ORDER  INTEGER NOT NULL,
  TYPE_ID       INTEGER NOT NULL
);
create index PS_POLICY_TYPE_ID_IDX on PS_POLICY (TYPE_ID);
