create index DNSKEY_URL_MON_LIST_SRC_IDX on DNSKEY_URL_MON_LIST (SRC);
create index DNSKEY_URL_MON_LIST_FIRST_POLL_IDX on DNSKEY_URL_MON_LIST (FIRST_POLL);
create index DNSKEY_URL_MON_LIST_LAST_POLL_IDX on DNSKEY_URL_MON_LIST (LAST_POLL);
create index DNSKEY_URL_MON_LIST_NEXT_POLL_IDX on DNSKEY_URL_MON_LIST (NEXT_POLL);
