#!/bin/bash

# subscribe to UCLA ndn node namespace

/usr/local/bin/ccndc add /ucla.edu/apps/lighting tcp borges.metwi.ucla.edu

# send any interest in namespace to ensure ccndc bi-directional if behind NAT

/home/lighting/ndn-lighting/ndn/signedInterest/signedNDNClient /ucla.edu/apps/lighting/test

echo "OK, ccndc route is now bi-directional"

# don't use old C version
#/home/lighting/ndn-lighting/ndn/signedData/signedNDNServer &> /home/lighting/in
terests.log

cd /home/lighting/ndn-lighting/python
/usr/bin/python controller.py controller_cfg  &> /home/lighting/interests.log
#tail -f /home/lighting/interests.log;


