#!/bin/bash
/home/lighting/ndn-lighting/ndn/signedData/signedNDNServer &
/home/lighting/ccn/ccnx/bin/ccndc add /ucla.edu/apps/lighting tcp borges.metwi.ucla.edu
/usr/bin/python /home/lighting/ndn-lighting/ndn/ColorBlast/ControlSocket.py &
/usr/bin/python /home/lighting/ndn-lighting/ndn/ArtNet.py 127.0.0.1 131.179.141.17
