# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='light-command.proto',
  package='',
  serialized_pb='\n\x13light-command.proto\"\xcc\x03\n\x13LightCommandMessage\x12\x33\n\x07\x63ommand\x18\x83\x01 \x02(\x0b\x32!.LightCommandMessage.LightCommand\x1a\xff\x02\n\x0cLightCommand\x12@\n\x07pattern\x18\x84\x01 \x02(\x0b\x32..LightCommandMessage.LightCommand.ColorPattern\x12\x0f\n\x06repeat\x18\x85\x01 \x01(\x08\x12>\n\nmixPattern\x18\x86\x01 \x01(\x0b\x32).LightCommandMessage.LightCommand.MixInfo\x1a+\n\x05\x43olor\x12\n\n\x01r\x18\x89\x01 \x02(\r\x12\n\n\x01g\x18\x8a\x01 \x02(\r\x12\n\n\x01\x62\x18\x8b\x01 \x02(\r\x1aH\n\x0c\x43olorPattern\x12\x38\n\x06\x63olors\x18\x87\x01 \x03(\x0b\x32\'.LightCommandMessage.LightCommand.Color\x1a\x65\n\x07MixInfo\x12\x42\n\tmixColors\x18\x84\x01 \x02(\x0b\x32..LightCommandMessage.LightCommand.ColorPattern\x12\x16\n\rmixProportion\x18\x88\x01 \x02(\x02')




_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLOR = descriptor.Descriptor(
  name='Color',
  full_name='LightCommandMessage.LightCommand.Color',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='r', full_name='LightCommandMessage.LightCommand.Color.r', index=0,
      number=137, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='g', full_name='LightCommandMessage.LightCommand.Color.g', index=1,
      number=138, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='b', full_name='LightCommandMessage.LightCommand.Color.b', index=2,
      number=139, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=264,
  serialized_end=307,
)

_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLORPATTERN = descriptor.Descriptor(
  name='ColorPattern',
  full_name='LightCommandMessage.LightCommand.ColorPattern',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='colors', full_name='LightCommandMessage.LightCommand.ColorPattern.colors', index=0,
      number=135, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=309,
  serialized_end=381,
)

_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_MIXINFO = descriptor.Descriptor(
  name='MixInfo',
  full_name='LightCommandMessage.LightCommand.MixInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mixColors', full_name='LightCommandMessage.LightCommand.MixInfo.mixColors', index=0,
      number=132, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mixProportion', full_name='LightCommandMessage.LightCommand.MixInfo.mixProportion', index=1,
      number=136, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=383,
  serialized_end=484,
)

_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND = descriptor.Descriptor(
  name='LightCommand',
  full_name='LightCommandMessage.LightCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pattern', full_name='LightCommandMessage.LightCommand.pattern', index=0,
      number=132, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeat', full_name='LightCommandMessage.LightCommand.repeat', index=1,
      number=133, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mixPattern', full_name='LightCommandMessage.LightCommand.mixPattern', index=2,
      number=134, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLOR, _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLORPATTERN, _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_MIXINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=101,
  serialized_end=484,
)

_LIGHTCOMMANDMESSAGE = descriptor.Descriptor(
  name='LightCommandMessage',
  full_name='LightCommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='LightCommandMessage.command', index=0,
      number=131, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=484,
)

_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLOR.containing_type = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND;
_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLORPATTERN.fields_by_name['colors'].message_type = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLOR
_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLORPATTERN.containing_type = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND;
_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_MIXINFO.fields_by_name['mixColors'].message_type = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLORPATTERN
_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_MIXINFO.containing_type = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND;
_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND.fields_by_name['pattern'].message_type = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLORPATTERN
_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND.fields_by_name['mixPattern'].message_type = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_MIXINFO
_LIGHTCOMMANDMESSAGE_LIGHTCOMMAND.containing_type = _LIGHTCOMMANDMESSAGE;
_LIGHTCOMMANDMESSAGE.fields_by_name['command'].message_type = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND
DESCRIPTOR.message_types_by_name['LightCommandMessage'] = _LIGHTCOMMANDMESSAGE

class LightCommandMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class LightCommand(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class Color(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLOR
      
      # @@protoc_insertion_point(class_scope:LightCommandMessage.LightCommand.Color)
    
    class ColorPattern(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_COLORPATTERN
      
      # @@protoc_insertion_point(class_scope:LightCommandMessage.LightCommand.ColorPattern)
    
    class MixInfo(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND_MIXINFO
      
      # @@protoc_insertion_point(class_scope:LightCommandMessage.LightCommand.MixInfo)
    DESCRIPTOR = _LIGHTCOMMANDMESSAGE_LIGHTCOMMAND
    
    # @@protoc_insertion_point(class_scope:LightCommandMessage.LightCommand)
  DESCRIPTOR = _LIGHTCOMMANDMESSAGE
  
  # @@protoc_insertion_point(class_scope:LightCommandMessage)

# @@protoc_insertion_point(module_scope)
